# Generated by Django 4.1.3 on 2022-11-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('date', models.DateField(verbose_name='تاریخ رزرو')),
                ('time', models.TimeField(verbose_name='زمان رزرو')),
                ('number', models.PositiveSmallIntegerField(verbose_name='تعداد نفرات رزروی')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزرو ها',
            },
        ),
    ]
