# Generated by Django 4.1.3 on 2022-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_app', '0003_alter_reservation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='number',
            field=models.PositiveSmallIntegerField(verbose_name='تعداد نفرات رزروی'),
        ),
    ]
