# Generated by Django 4.1.3 on 2022-11-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='اندازه عکس ها باید 1200x800 پیکسل باشند', upload_to='Gallery', verbose_name='عکس گالری')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='اندازه عکس ها باید 1920x1280 پیکسل باشند', upload_to='Slider', verbose_name='عکس اسلایدر')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
    ]
