# Generated by Django 4.1.3 on 2022-11-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'عکس گالری', 'verbose_name_plural': 'عکس های گالری'},
        ),
        migrations.AlterModelOptions(
            name='homeslider',
            options={'verbose_name': 'عکس اسلایدر', 'verbose_name_plural': 'عکس های اسلایدر'},
        ),
    ]
