# Generated by Django 4.1.3 on 2022-11-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('drinks', 'نوشیدنی'), ('lunch', 'ناهار'), ('dinner', 'شام')], max_length=20, verbose_name='نوع غذا')),
                ('name', models.CharField(max_length=20, verbose_name='اسم غذا')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت غذا')),
                ('descripion', models.TextField(max_length=40, verbose_name='توضیحات غذا')),
                ('image', models.ImageField(help_text='تصاویر باید در سایز 800x480 باشند', upload_to='Foods', verbose_name='عکس غذا')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('status', models.BooleanField(default=False, help_text='وضعیت انتشار در سایت', verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
            },
        ),
    ]
