# Generated by Django 4.1.3 on 2022-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='situation',
            field=models.BooleanField(default=True, verbose_name='موجوو بودن غذا'),
        ),
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, help_text='این فیلد به صورت خودکار تکمیل میشود', unique=True, verbose_name='اسلاگ'),
        ),
    ]
