# Generated by Django 4.1.3 on 2022-11-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_food_situation_food_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='situation',
            field=models.BooleanField(default=True, verbose_name='موجود بودن غذا'),
        ),
    ]
