# Generated by Django 4.1.3 on 2022-12-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_alter_food_situation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True, verbose_name='عنوان تگ')),
                ('slug', models.SlugField(blank=True, help_text='این فیلد به صورت خودکار تکمیل میشود', unique=True, verbose_name='اسلاگ')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('food', models.ForeignKey(help_text='کامنت مدنظر برای چه مقاله ای هست', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='food_app.food', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, help_text='اگر این کامنت درجواب کامنت دیگری باشد تکمیل میگردد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='food_app.comment', verbose_name='جواب کامنت')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='food_app.tag', verbose_name='تگ ها'),
        ),
    ]
