# Generated by Django 4.1.3 on 2022-12-19 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_slug_alter_blog_author_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی')),
                ('text', models.TextField(verbose_name='متن کامنت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('blog', models.ForeignKey(help_text='کامنت مدنظر برای چه مقاله ای هست', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blog', verbose_name='مقاله')),
                ('parent', models.ForeignKey(blank=True, help_text='اگر این کامنت درجواب کامنت دیگری باشد تکمیل میگردد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog_app.comment', verbose_name='جواب کامنت')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
